service: synonym
frameworkVersion: '3'

custom:
  s3Bucket: ${param:s3Bucket}
  imageArn: ${param:imageArn}


provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  hello:
    handler: src.handler.hello

stepFunctions:
  stateMachines:
    synonymFunc:
      role: 
        Fn::GetAtt: ["StateMachineRole", "Arn"]
      name: synonym-generator
      definition:
        Comment: Synonym Generator
        StartAt: SageMaker CreateTrainingJob
        States:
          SageMaker CreateEndpoint:
            End: true
            Parameters:
              EndpointConfigName.$: States.Format('Synonym-{}', $$.Execution.Name)
              EndpointName.$: States.Format('Synonym-{}', $$.Execution.Name)
            Resource: arn:aws:states:::sagemaker:createEndpoint
            ResultPath: $.endpoint_result
            Type: Task
          SageMaker CreateEndpointConfig:
            Next: SageMaker CreateEndpoint
            Parameters:
              EndpointConfigName.$: States.Format('Synonym-{}', $$.Execution.Name)
              ProductionVariants:
              - ModelName.$: States.Format('Synonym-{}', $$.Execution.Name)
                ServerlessConfig:
                  MaxConcurrency: 20
                  MemorySizeInMB: 3072
                VariantName.$: States.Format('Synonym-{}', $$.Execution.Name)
            Resource: arn:aws:states:::sagemaker:createEndpointConfig
            ResultPath: $.endpoint_config_result
            Type: Task
          SageMaker CreateModel:
            Next: SageMaker CreateEndpointConfig
            Parameters:
              EnableNetworkIsolation: false
              ExecutionRoleArn:
                Fn::GetAtt: ["SageMakerExecutionRole", "Arn"]
              ModelName.$: States.Format('Synonym-{}', $$.Execution.Name)
              PrimaryContainer:
                Image: ${self:custom.imageArn}
                Mode: SingleModel
                ModelDataUrl.$: $.training_result.ModelArtifacts.S3ModelArtifacts
            Resource: arn:aws:states:::sagemaker:createModel
            ResultPath: $.model_result
            Type: Task
          SageMaker CreateTrainingJob:
            Next: SageMaker CreateModel
            Parameters:
              AlgorithmSpecification:
                TrainingImage:  ${self:custom.imageArn}
                TrainingInputMode: File
              EnableInterContainerTrafficEncryption: false
              EnableManagedSpotTraining: false
              EnableNetworkIsolation: false
              Environment:
                foo: bar
              HyperParameters:
                hoge: fuga
              InputDataConfig:
              - ChannelName: train
                CompressionType: None
                ContentType: text/plain
                DataSource:
                  S3DataSource:
                    S3DataDistributionType: FullyReplicated
                    S3DataType: S3Prefix
                    S3Uri: s3://${self:custom.s3Bucket}/synonym/data/
                InputMode: File
              OutputDataConfig:
                S3OutputPath: s3://${self:custom.s3Bucket}/synonym/model/
              ResourceConfig:
                InstanceCount: 1
                InstanceType: ml.m4.xlarge
                VolumeSizeInGB: 16
              RoleArn:
                Fn::GetAtt: ["SageMakerExecutionRole", "Arn"]
              StoppingCondition:
                MaxRuntimeInSeconds: 3600
              TrainingJobName.$: States.Format('Synonym-{}', $$.Execution.Name)
            Resource: arn:aws:states:::sagemaker:createTrainingJob.sync
            ResultPath: $.training_result
            Type: Task


resources:
  Resources:
    SageMakerExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: SynonymGeneratorSageMakerExecutionRole
        Path: /service-role/
        AssumeRolePolicyDocument:
          Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
              - sagemaker.amazonaws.com
              - states.amazonaws.com
              - events.amazonaws.com
              - apigateway.amazonaws.com
              - glue.amazonaws.com
              - lambda.amazonaws.com
              - codepipeline.amazonaws.com
              - cloudformation.amazonaws.com
              - codebuild.amazonaws.com
              - firehose.amazonaws.com
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/PowerUserAccess

    StateMachineRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: SynonymGeneratorStateMachineRole
        Path: /service-role/
        AssumeRolePolicyDocument:
          Statement:
          - Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
            Action:
              - sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/PowerUserAccess
        Policies:
          - PolicyName: statePolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Action:
                - iam:PassRole
                Condition:
                  StringEquals:
                    iam:PassedToService: sagemaker.amazonaws.com
                Effect: Allow
                Resource:
                - Fn::GetAtt: ["SageMakerExecutionRole", "Arn"]


plugins:
  - serverless-step-functions